version: "3.8"

services:
  mongodb:
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    container_name: schedule_db

  mongo-express:
    image: mongo-express
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=${DATABASE_URL}
    depends_on:
      - mongodb